### ISSUE TITLE
Monsters attacks bug

### ISSUE THREAD

**Issue by tarantonio** [TwistedScorpio/Nostalrius#38] opened 2019-04-12 11:23 UTC
It seems to be a problem with monsters, they are not attacking players as the xml file is coded.
Examples:
Orc spearman, dragon, warlock...

An orc spearman can stay minutes without any spear attack.
![orcs](https://user-images.githubusercontent.com/7066891/56033946-1bea6f80-5d26-11e9-9472-efa352fea8d7.gif)
Compared to OTHire:
![orcsothire](https://user-images.githubusercontent.com/7066891/56035885-b39e8c80-5d2b-11e9-8978-bae4c524b8a4.gif)

**Comment by TwistedScorpio** [comment] 2019-04-13 17:24
As people have reported on otland, it seems the issue is only related to the random function from TFS, that calling uniform_random solves it instead, if someone could test and report, would be appreciated.

**Comment by TwistedScorpio** [comment] 2019-04-13 20:11
Should be fixed, [normal_random vs uniform_random](https://otland.net/threads/nostalrius-7-7.262406/post-2552267) .

**Closed by TwistedScorpio** 2019-04-13 20:11 UTC
